language: python
python:
  - "3.6"
install:
  - "pip install -r requirements-dev.txt"
  - "pip install codecov"
script:
  - "python setup.py test"
after_success:
  - "coverage report --skip-covered"
  - codecov
